# Generated by Django 2.1.3 on 2019-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbank',
            name='answer',
            field=models.CharField(max_length=2),
        ),
    ]
